### PR TITLE
Adds compatibility with OMP 3.4

### PR DESCRIPTION
**Pull request by YvesLepidus**
Hello! :smile: 
We added compatibility with OMP 3.4, using series to define upcoming publications. Since it can be compatible with two applications, we recommend using common terms from OJS and OMP. For example, changing 'Forthcoming Articles Plugin' to 'Forthcoming Publications Plugin'. We are available to contribute to this, if necessary, in Brazilian Portuguese.

### CODE REVIEW

**Comment by ajnyga** [comment]
Hi!

Thank you for the contribution. Can you describe a bit the use case for having this in OMP? In OJS the idea is to publish something that does not belong to a specific issue yet, but in OMP I am not entirely sure what the use case is while the books are not tied to an object like issue?

I am maybe just careful not to make the plugin too complicated

**Comment by diegoabadan** [comment]
Hi @ajnyga !

A publisher adopting OMP wants to display books that are about to be released. The strategy adopted is to use a series. Monographs registered in this series will be displayed in advance.

**Comment by ajnyga** [comment]
Is it not technically possible to publish without an series in OMP?

**Comment by YvesLepidus** [comment]
> Is it not technically possible to publish without an series in OMP?

It is possible to publish a monograph without an associated series. The publisher needs to have at least one series to receive submissions, and the author must select a series to submit. However, once submitted, if we remove the series from the submission, it can be published.

**Comment by ajnyga** [comment]
Just thinking whether it makes sense in OMP to have this plugin if you can publish things without a series. Or alternatively you could have a series called Forthcoming and this plugin would not have to do much at all. A lot of the functionaly is just to hide the standard issue toc.

My concern maybe is that does this make the plugin more hard to maintain.

Just want to have this conversation, I definitely value your contributions!

**Comment by diegoabadan** [comment]
Hi @ajnyga 

I spoke with our development team and the people involved in this PR explained that they were trying to generalize a client's need so that other potential OMP users could take advantage of it, and this OJS plugin seemed like the best way to go at the time.

We understand your concern about the increase in complexity, and even if the way they chose to resolve the issue was good, we can disregard this PR. If we see new similar demands, we can rethink the matter.

Thank you!

**Pull request closed without merging**
